### ISSUE TITLE
Clojure 9 compatibility

### ISSUE THREAD

**Issue by SerCeMan** [ptaoussanis/encore#29] opened 2016-07-01 12:12 UTC
Hi!

I tried to run my app with clojure 9 and I've got this error:

```
Caused by: clojure.lang.ExceptionInfo: Invariant violation in `taoensso.encore:?` [pred-form, val]:
 [(pos-int? ttl-ms), 60000]
`pred-form` error: java.lang.IllegalStateException: Attempting to call unbound fn: #'taoensso.encore/pos-int? {:*?data* nil, :elidable? true, :dt #inst "2016-07-01T12:03:24.801-00:00", :val 60000, :ns-str "taoensso.encore", :val-type java.lang.Long, :?err #error {
 :cause "Attempting to call unbound fn: #'taoensso.encore/pos-int?"
 :via
 [{:type java.lang.IllegalStateException
   :message "Attempting to call unbound fn: #'taoensso.encore/pos-int?"
   :at [clojure.lang.Var$Unbound throwArity "Var.java" 43]}]
 :trace
 [[clojure.lang.Var$Unbound throwArity "Var.java" 43]
  [clojure.lang.AFn invoke "AFn.java" 32]
  [taoensso.encore$memoize_STAR_$fn__14881 invoke "encore.clj" 1630]
  [taoensso.encore$memoize_STAR_ invokeStatic "encore.clj" 1630]
  [taoensso.encore$memoize_STAR_ invoke "encore.clj" 1600]
  [taoensso.timbre.appenders.core__init load nil 107]
  [taoensso.timbre.appenders.core__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2181]
  [clojure.lang.RT classForName "RT.java" 2190]
  [clojure.lang.RT loadClassForName "RT.java" 2209]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__7570 invoke "core.clj" 6001]
  [clojure.core$load invokeStatic "core.clj" 6000]
  [clojure.core$load doInvoke "core.clj" 5984]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.core$load_one invokeStatic "core.clj" 5805]
  [clojure.core$load_one invoke "core.clj" 5800]
  [clojure.core$load_lib$fn__7515 invoke "core.clj" 5845]
  [clojure.core$load_lib invokeStatic "core.clj" 5844]
  [clojure.core$load_lib doInvoke "core.clj" 5825]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$load_libs invokeStatic "core.clj" 5882]
  [clojure.core$load_libs doInvoke "core.clj" 5866]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$require invokeStatic "core.clj" 5904]
  [clojure.core$require doInvoke "core.clj" 5904]
  [clojure.lang.RestFn invoke "RestFn.java" 457]
  [taoensso.timbre$loading__5569__auto____15132 invoke "timbre.clj" 1]
  [taoensso.timbre__init load nil 1]
  [taoensso.timbre__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2181]
  [clojure.lang.RT classForName "RT.java" 2190]
  [clojure.lang.RT loadClassForName "RT.java" 2209]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__7570 invoke "core.clj" 6001]
  [clojure.core$load invokeStatic "core.clj" 6000]
  [clojure.core$load doInvoke "core.clj" 5984]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.core$load_one invokeStatic "core.clj" 5805]
  [clojure.core$load_one invoke "core.clj" 5800]
  [clojure.core$load_lib$fn__7515 invoke "core.clj" 5845]
  [clojure.core$load_lib invokeStatic "core.clj" 5844]
  [clojure.core$load_lib doInvoke "core.clj" 5825]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$load_libs invokeStatic "core.clj" 5882]
  [clojure.core$load_libs doInvoke "core.clj" 5866]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$require invokeStatic "core.clj" 5904]
  [clojure.core$require doInvoke "core.clj" 5904]
  [clojure.lang.RestFn invoke "RestFn.java" 482]
  [taoensso.sente$loading__5569__auto____14187 invoke "sente.clj" 1]
  [taoensso.sente__init load nil 1]
  [taoensso.sente__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2181]
  [clojure.lang.RT classForName "RT.java" 2190]
  [clojure.lang.RT loadClassForName "RT.java" 2209]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__7570 invoke "core.clj" 6001]
  [clojure.core$load invokeStatic "core.clj" 6000]
  [clojure.core$load doInvoke "core.clj" 5984]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.core$load_one invokeStatic "core.clj" 5805]
  [clojure.core$load_one invoke "core.clj" 5800]
  [clojure.core$load_lib$fn__7515 invoke "core.clj" 5845]
  [clojure.core$load_lib invokeStatic "core.clj" 5844]
  [clojure.core$load_lib doInvoke "core.clj" 5825]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$load_libs invokeStatic "core.clj" 5882]
  [clojure.core$load_libs doInvoke "core.clj" 5866]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$require invokeStatic "core.clj" 5904]
  [clojure.core$require doInvoke "core.clj" 5904]
  [clojure.lang.RestFn invoke "RestFn.java" 457]
  [dashboard.handlers$eval26$loading__7456__auto____27 invoke "handlers.clj" 1]
  [dashboard.handlers$eval26 invokeStatic "handlers.clj" 1]
  [dashboard.handlers$eval26 invoke "handlers.clj" 1]
  [clojure.lang.Compiler eval "Compiler.java" 6946]
  [clojure.lang.Compiler eval "Compiler.java" 6935]
  [clojure.lang.Compiler load "Compiler.java" 7398]
  [clojure.lang.RT loadResourceScript "RT.java" 372]
  [clojure.lang.RT loadResourceScript "RT.java" 363]
  [clojure.lang.RT load "RT.java" 453]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__7570 invoke "core.clj" 6001]
  [clojure.core$load invokeStatic "core.clj" 6000]
  [clojure.core$load doInvoke "core.clj" 5984]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.core$load_one invokeStatic "core.clj" 5805]
  [clojure.core$load_one invoke "core.clj" 5800]
  [clojure.core$load_lib$fn__7515 invoke "core.clj" 5845]
  [clojure.core$load_lib invokeStatic "core.clj" 5844]
  [clojure.core$load_lib doInvoke "core.clj" 5825]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$load_libs invokeStatic "core.clj" 5882]
  [clojure.core$load_libs doInvoke "core.clj" 5866]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$require invokeStatic "core.clj" 5904]
  [clojure.core$require doInvoke "core.clj" 5904]
  [clojure.lang.RestFn invoke "RestFn.java" 3894]
  [dashboard.core$loading__5569__auto____40 invoke "core.clj" 1]
  [dashboard.core__init load nil 1]
  [dashboard.core__init <clinit> nil -1]
  [java.lang.Class forName0 "Class.java" -2]
  [java.lang.Class forName "Class.java" 348]
  [clojure.lang.RT classForName "RT.java" 2181]
  [clojure.lang.RT classForName "RT.java" 2190]
  [clojure.lang.RT loadClassForName "RT.java" 2209]
  [clojure.lang.RT load "RT.java" 443]
  [clojure.lang.RT load "RT.java" 419]
  [clojure.core$load$fn__7570 invoke "core.clj" 6001]
  [clojure.core$load invokeStatic "core.clj" 6000]
  [clojure.core$load doInvoke "core.clj" 5984]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.core$load_one invokeStatic "core.clj" 5805]
  [clojure.core$load_one invoke "core.clj" 5800]
  [clojure.core$load_lib$fn__7515 invoke "core.clj" 5845]
  [clojure.core$load_lib invokeStatic "core.clj" 5844]
  [clojure.core$load_lib doInvoke "core.clj" 5825]
  [clojure.lang.RestFn applyTo "RestFn.java" 142]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$load_libs invokeStatic "core.clj" 5882]
  [clojure.core$load_libs doInvoke "core.clj" 5866]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 653]
  [clojure.core$require invokeStatic "core.clj" 5904]
  [clojure.core$require doInvoke "core.clj" 5904]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [user$eval17 invokeStatic "form-init6185835984960955702.clj" 1]
  [user$eval17 invoke "form-init6185835984960955702.clj" 1]
  [clojure.lang.Compiler eval "Compiler.java" 6946]
  [clojure.lang.Compiler eval "Compiler.java" 6935]
  [clojure.lang.Compiler eval "Compiler.java" 6935]
  [clojure.lang.Compiler load "Compiler.java" 7398]
  [clojure.lang.Compiler loadFile "Compiler.java" 7336]
  [clojure.main$load_script invokeStatic "main.clj" 275]
  [clojure.main$init_opt invokeStatic "main.clj" 277]
  [clojure.main$init_opt invoke "main.clj" 277]
  [clojure.main$initialize invokeStatic "main.clj" 308]
  [clojure.main$null_opt invokeStatic "main.clj" 342]
  [clojure.main$null_opt invoke "main.clj" 339]
  [clojure.main$main invokeStatic "main.clj" 421]
  [clojure.main$main doInvoke "main.clj" 384]
  [clojure.lang.RestFn invoke "RestFn.java" 421]
  [clojure.lang.Var invoke "Var.java" 383]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.Var applyTo "Var.java" 700]
  [clojure.main main "main.java" 37]]}, :*assert* true, :?data nil, :?line nil, :form-str "(pos-int? ttl-ms)"}
	at clojure.core$ex_info.invokeStatic(core.clj:4718)
	at clojure.core$ex_info.invoke(core.clj:4718)
	at taoensso.truss.impl$_invar_violation_BANG_.invokeStatic(impl.clj:151)
	at taoensso.truss.impl$_invar_violation_BANG_.invoke(impl.clj:122)
	at taoensso.encore$memoize_STAR_$fn__14881.invoke(encore.clj:1630)
	at taoensso.encore$memoize_STAR_.invokeStatic(encore.clj:1630)
	at taoensso.encore$memoize_STAR_.invoke(encore.clj:1600)
	at taoensso.timbre.appenders.core__init.load(Unknown Source)
	at taoensso.timbre.appenders.core__init.<clinit>(Unknown Source)
	... 157 more
```

**Comment by ptaoussanis** [comment] 2016-07-01 13:27
Hi Sergey, should be compatible with Clojure 1.9 - please check the version that you're using. Latest is `[com.taoensso/encore "2.59.0"]`.

(You might want/need `lein clean` to remove old build artifacts and/or `lein deps :tree` to confirm that you're pulling in the correct/latest version of encore).

Cheers!

**Comment by ptaoussanis** [comment] 2016-07-04 04:26
Just checked against Clojure 1.9.0-alpha8 and that seems to be alright too. Going to assume that you just needed to pull in a newer version of encore, closing. Please feel free to reopen if you're still having issues.

**Closed by ptaoussanis** 2016-07-04 04:26 UTC

**Comment by vadali** [comment] 2016-08-11 00:12
I am getting the same error with `clojure "1.9.0-alpha10"`. 
```
Caused by: clojure.lang.ExceptionInfo: Invariant violation in `taoensso.encore:?` [pred-form, val]:
 [(pos-int? ttl-ms), 60000]
`pred-form` error: java.lang.IllegalStateException: Attempting to call unbound fn: #'taoensso.encore/pos-int? {:*?data* nil, :elidable? true, :dt #inst "2016-08-11T00:07:37.044-00:00", :val 60000, :ns-str "taoensso.encore", :val-type java.lang.Long, :?err #error {
 :cause "Attempting to call unbound fn: #'taoensso.encore/pos-int?"
 :via
 [{:type java.lang.IllegalStateException
   :message "Attempting to call unbound fn: #'taoensso.encore/pos-int?"
   :at [clojure.lang.Var$Unbound throwArity "Var.java" 43]}]

```

Did `lein clean` and `lein deps :tree`, where I am seeing:

```
 [com.taoensso/timbre "4.7.0"]
   [com.taoensso/encore "2.64.1"]
     [com.taoensso/truss "1.3.3"]
     [org.clojure/tools.reader "0.10.0"]
   [io.aviso/pretty "0.1.28"]
[org.clojure/clojure "1.9.0-alpha10"]
```
Trimmed irrelevant entries, and there were no conflicts nor other versions of `taoensso` projects..

What am I missing?

Thanks!

**Comment by mpenet** [comment] 2016-09-29 13:25
Same here while trying to upgrade to alpha13 + `com.taoensso/encore "2.82.1"` (confirmed with deps tree)

`Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'taoensso.encore/-invar-violation!`

**Comment by mpenet** [comment] 2016-09-29 13:37
without upgrading encore I get this one fyi:

```
Caused by: clojure.lang.ExceptionInfo: Invariant violation in `taoensso.encore:1782` [pred-form, val]:
 [(pos-int? ttl-ms), 60000]
`pred-form` error: java.lang.IllegalStateException: Attempting to call unbound fn: #'taoensso.encore/pos-int? {:?form nil, :instant 1475156138684, :ns "taoensso.encore", :elidable? true, :val 60000, :val-type java.lang.Long, :?err #error {
 :cause "Attempting to call unbound fn: #'taoensso.encore/pos-int?"
 :via
 [{:type java.lang.IllegalStateException
   :message "Attempting to call unbound fn: #'taoensso.encore/pos-int?"
   :at [clojure.lang.Var$Unbound throwArity "Var.java" 43]}]
 :trace
```

**Comment by ptaoussanis** [comment] 2016-09-30 03:13
Hi Max,

Just tested Encore 2.82.1 against Clojure 1.9.0-alpha13 and everything still seems to be working on my end.

Only possible cause for the error that you're seeing (that I'm aware of) - is that Clojure core's `pos-int?` isn't being excluded as it should be as of Encore [2.56.1](https://github.com/ptaoussanis/encore/commit/55a8c6125825e3235c0a3555701b1e48ba83e999).

Every case of this error that I've seen in person has been the result of a dependency conflict and/or stale build artifacts somehow getting to the Cljs compiler.

If you've confirmed that the Cljs compiler is indeed certainly getting the correct dependencies without any stale artifacts, unfortunately don't have any other obvious ideas of what to try.

Would be happy to investigate further if someone can provide a minimal reproducible example?

Thanks!

**Comment by mpenet** [comment] 2016-09-30 04:07
Hi Peter,

This was a problem with direct linking + AOT in one of my dependencies.
Sorry about the noise!

Max

**Comment by ptaoussanis** [comment] 2016-09-30 04:18
No problem, happy you found the culprit. Thanks for the update, cheers :-)
