### ISSUE TITLE
`nil` causes a "%d" format to throw a java.util.IllegalFormatConversionException

### ISSUE THREAD

**Issue by glittershark** [ptaoussanis/encore#32] opened 2016-09-10 15:34 UTC
Because of [this conversion](https://github.com/ptaoussanis/encore/blob/master/src/taoensso/encore.cljx#L2127), `(format* "%d" nil)` (discovered via Timbre) is throwing a `java.util.IllegalFormatConversionException`:

``` clojure
(user) λ (taoensso.timbre/infof "%d" nil)

java.util.IllegalFormatConversionException: d != java.lang.String
```

**Comment by ptaoussanis** [comment] 2016-09-11 03:02
Hi Griffin, thanks for the report (and for identifying the root cause).

To be clear: you'd prefer `(taoensso.timbre/infof "%d" nil)` return "nil" as `(format "%d" nil)` returns "null"?

Any chance you could motivate that a little? I'm not familiar with anyone intentionally depending on nil-formatting behaviour and wonder whether the current implementation isn't more likely to catch unintended bugs?

Is the argument primarily to maintain API compatibility with `core/format`, or are you aware of people actually intentionally depending on specific nil-formatting behaviour?

**Comment by glittershark** [comment] 2016-09-16 19:13
I log every HTTP request along with the (numeric) ID of the user who generated that request, but sometimes the user ID is null

**Comment by glittershark** [comment] 2016-09-16 19:14
Prior to upgrading to the version of Timbre that used encore for string formatting, it'd just log `user_id=null`

**Comment by ptaoussanis** [comment] 2016-09-16 20:49
Hi there, just to rule this out: is there a reason in this case that you'd specifically want "%d" as opposed to "%s"?

**Comment by glittershark** [comment] 2016-09-16 20:51
I guess not in this specific case, no - that's actually the workaround I have committed right now. So if you want to let this issue languish until someone comes up with a more compelling use case that's fine by me

**Comment by ptaoussanis** [comment] 2016-09-16 20:56
Honestly, don't feel strongly about this one way or the other. Will think about it a little more though. Thanks for bringing this up.

**Comment by ptaoussanis** [comment] 2017-02-13 15:27
So think I'd probably rather err on the side of catching unintended behavior here (vs compatibility with `clojure.core/format`).

Closing, but still open to hear counter-arguments if you or anyone else feels like reopening :-)

Cheers!

**Closed by ptaoussanis** 2017-02-13 15:27 UTC
Labels: ideas welcome
